Update 01-building-blocks.yml
all steps included

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -4,6 +4,21 @@ jobs:
  echo-hello:
     runs-on: ubuntu-latest
     steps:
-    - id: say-hello
+    - name: say-hello
       run: echo "Hello, World!"
+ echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+    - name: failed-step
+      run: |
+       echo "I "
+       echo "will"
+       echo "fail."
+       exit 1
+    - name: Say goodbye
+      run: echo "Goodbye!"
+    - name: Last step
+      run: echo "Last step with zero exit code"
+           exit 0
+   
       
